server:
  port: 8888
spring:
  application:
    name: reto-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jefernas/Bootcamp.git
        search paths:
         - '*service*'

