server:
  port: 8081
spring:
  application:
    name: product-service2
  cloud:
   config:
   import-check: false
   

  
eureka:
  client:
  serviceUrl:
      defaultZone: http://localhost:8761/eureka/
